services:
  temp-server:
    command: java -jar -XX:+UseSerialGC -Xss512k -XX:MaxRAM=72m app.jar
    image: lrprojects/tempserver:1.0.0-SNAPSHOT
    restart: unless-stopped
    ports:
      - 8081:8080
    env_file:
      -  .env
    networks:
      - influxdb-network
      - frontend
      - db

    labels:
      - traefik.enable=true
      - traefik.http.routers.tempserver.rule=Host(`temppi.thinkpad.lr-projects.de`)
      - traefik.http.routers.tempserver.entrypoints=websecure
      - traefik.http.routers.tempserver.tls=true
      - traefik.http.routers.tempserver.tls.certresolver=cloudflare
      - traefik.http.services.tempserver.loadbalancer.server.port=8080
      - traefik.docker.network=frontend
networks:
  influxdb-network:
    external: true
  frontend:
    external: true
  db:
    external: true

