global:
  forget:
    keep-last: 5 # always keep at least 5 snapshots
    keep-daily: 4 # keep 4 last daily snapshots
    keep-weekly: 1 # keep 1 last weekly snapshots
    keep-monthly: 12 # keep 12 last monthly snapshots
    keep-yearly: 7 # keep 7 last yearly snapshots


backends:
  drive:
    type: rclone
    path: drive:backup/medion
    requirekey: false
    env: {}
    rest:
      user: ""
      password: ""
  local:
    type: local
    path: /home/lr/backup
    key: ""
    requirekey: false
    env: {}
    rest:
      user: ""
      password: ""
locations:
  docker-tags:
    from:
    - ./.backup
    to:
    - local
    - drive
    type: ""
    hooks:
      dir: ""
      prevalidate: []
      before:
      - docker ps -q | while read cid; do
          cname=$(docker inspect -f '{{.Name}}' "$cid" | sed 's#^/##')
          image=$(docker inspect -f '{{.Config.Image}}' "$cid")
          digest=$(docker image inspect "$image" --format '{{index .RepoDigests 0}}' 2>/dev/null || echo "none")
          printf "%s\t%s\t%s\n" "$cname" "$image" "$digest"
        done > ./.backup/docker-tags.txt
      after: []
      success: []
      failure: []
    forget: prune
  immich:
    from:
    - ./immich-app
    type: ""
    to:
    - local
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success: []
      failure: []
    cron: ""
    options:
      backup:
        exclude:
        - '*/postgres/*'
        - '*/library/thumbs/*'
        - '*/library/encoded-video/*'
    copyoption: {}
    forget: prune
  jellyfin:
    from:
    - ./jellyfin
    type: ""
    to:
    - local
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success: []
      failure: []
    cron: ""
    options: {}
    copyoption: {}
    forget: prune
  logging:
    from:
    - ./logging
    type: ""
    to:
    - local
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success: []
      failure: []
    cron: ""
    options:
      backup:
        exclude:
        - '*/influx_backup/*'
        - '*/influx/influx_data/*'
    copyoption: {}
    forget: prune
  pihole:
    from:
    - ./pi-hole
    type: ""
    to:
    - local
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success: []
      failure: []
    cron: ""
    options: {}
    copyoption: {}
    forget: prune
  pocketid:
    from:
    - ./pocket-id
    type: ""
    to:
    - local
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success: []
      failure: []
    cron: ""
    options: {}
    copyoption: {}
    forget: prune
  portfolio:
    from:
    - ./portfolio
    type: ""
    to:
    - local
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success: []
      failure: []
    cron: ""
    options: {}
    copyoption: {}
    forget: prune
  stick-it-homepage:
    from:
    - ./stick-it-homepage
    type: ""
    to:
    - local
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success: []
      failure: []
    cron: ""
    options: {}
    copyoption: {}
    forget: prune
  traefik:
    from:
    - ./traefik
    type: ""
    to:
    - local
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success: []
      failure: []
    cron: ""
    options: {}
    copyoption: {}
    forget: prune
version: 2
