backends:
  drive:
    type: rclone
    path: drive:backup/medion
    key: ""
    requirekey: false
    env: {}
    rest:
      user: ""
      password: ""
    options: {}
  local:
    type: local
    path: /data/backup
    key: ""
    requirekey: false
    env: {}
    rest:
      user: ""
      password: ""
    options: {}
  nas:
    type: sftp
    path: nas:/backup_medion
    key: ""
    requirekey: false
    env: {}
    rest:
      user: ""
      password: ""
    options: {}
global:
  forget:
    keep-daily: 4
    keep-last: 5
    keep-monthly: 12
    keep-weekly: 1
    keep-yearly: 7
locations:
  docker-tags:
    from:
    - ./.backup
    type: ""
    to:
    - local
    - nas
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: /hooks/docker-tags-hook.sh
      after: []
      success:
      - python3 /hooks/influx-hook.py --host medion --service docker-tags --status
        success
      failure:
      - python3 /hooks/influx-hook.py --host medion --service docker-tags --status
        failure
    cron: ""
    options: {}
    copyoption: {}
  immich:
    from:
    - ./immich-app
    type: ""
    to:
    - local
    - nas
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success:
      - python3 /hooks/influx-hook.py --host medion --service immich --status
        success
      failure:
      - python3 /hooks/influx-hook.py --host medion --service immich --status
        failure
    cron: ""
    options:
      backup:
        exclude:
        - '*/postgres/*'
        - '*/library/thumbs/*'
        - '*/library/encoded-video/*'
    copyoption: {}
  jellyfin:
    from:
    - ./jellyfin
    type: ""
    to:
    - local
    - nas
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success:
      - python3 /hooks/influx-hook.py --host medion --service jellyfin --status
        success
      failure:
      - python3 /hooks/influx-hook.py --host medion --service jellyfin --status
        failure
    cron: ""
    options: {}
    copyoption: {}
  logging:
    from:
    - ./logging
    type: ""
    to:
    - local
    - nas
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success:
      - python3 /hooks/influx-hook.py --host medion --service logging --status
        success
      failure:
      - python3 /hooks/influx-hook.py --host medion --service logging --status
        failure
    cron: ""
    options:
      backup:
        exclude:
        - '*/influx_backup/*'
        - '*/influx/influx_data/*'
        - '*/prometheus/data/*'
    copyoption: {}
  nextcloud:
    from:
    - ./nextcloud
    type: ""
    to:
    - local
    - nas
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before:
      - docker exec -u root nextcloud-database-1 apt update
      - docker exec -u root nextcloud-database-1 apt install -y mysql-client
      - docker exec nextcloud-nextcloud-1 /var/www/html/occ maintenance:mode  --on
      - set -a;source nextcloud/.env;set +a;docker exec -e MYSQL_PWD="$NEXTCLOUD_DB_PASSWORD"
        nextcloud-database-1 mysqldump --single-transaction --column-statistics=0
        -h localhost -u nextcloud  nextcloud > ./nextcloud/backup/nextcloud.bak
      after:
      - docker exec nextcloud-nextcloud-1 /var/www/html/occ maintenance:mode  --off
      - unset $(grep -v '^#' nextcloud/.env | sed -E 's/(.*)=.*/\1/' | xargs)
      success:
      - python3 /hooks/influx-hook.py --host medion --service nextcloud --status
        success
      failure:
      - python3 /hooks/influx-hook.py --host medion --service nextcloud --status
        failure
    cron: ""
    options: {}
    copyoption: {}
  pocketid:
    from:
    - ./pocket-id
    type: ""
    to:
    - local
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success:
      - python3 /hooks/influx-hook.py --host medion --service pocketid --status
        success
      failure:
      - python3 /hooks/influx-hook.py --host medion --service pocketid --status
        failure
    cron: ""
    options: {}
    copyoption: {}
  stick-it-homepage:
    from:
    - ./stick-it-homepage
    type: ""
    to:
    - local
    - nas
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success:
      - python3 /hooks/influx-hook.py --host medion --service stick-it-homepage
        --status success
      failure:
      - python3 /hooks/influx-hook.py --host medion --service stick-it-homepage
        --status failure
    cron: ""
    options: {}
    copyoption: {}
  traefik:
    from:
    - ./traefik
    type: ""
    to:
    - local
    - nas
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success:
      - python3 /hooks/influx-hook.py --host medion --service traefik --status
        success
      failure:
      - python3 /hooks/influx-hook.py --host medion --service traefik --status
        failure
    cron: ""
    options: {}
    copyoption: {}
  adguard:
    from:
    - ./adguard
    type: ""
    to:
    - local
    - nas
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success:
      - python3 /hooks/influx-hook.py --host medion --service adguard --status success
      failure:
      - python3 /hooks/influx-hook.py --host medion --service adguard --status failure
    cron: ""
    options: {}
    copyoption: {}
version: 2
