# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4080:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_webserver_api_password: <PASSWORD> # TODO
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    cap_add:
    # See 
      # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities 
      # pi-hole: Required if you are using Pi-hole as 
      # your DHCP server, else not needed external: 
      # true
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP 
      # client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more 
      # processing time
      - SYS_NICE
