services:
  influxdb:
    image: influxdb:2.6-alpine
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: lr-projects
      DOCKER_INFLUXDB_INIT_BUCKET: home
    volumes:
      - ./influx/influx_data:/var/lib/influxdb2
      - ./influx/influx_config:/etc/influxdb2
    networks:
      - influxdb-network
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.influx.rule=Host(`influx.thinkpad.lr-projects.de`)
      - traefik.http.routers.influx.entrypoints=websecure
      - traefik.http.routers.influx.tls=true
      - traefik.http.routers.influx.tls.certresolver=cloudflare
      - traefik.http.services.influx.loadbalancer.server.port=8086

  telegraf:
    image: telegraf:1.31-alpine
    restart: unless-stopped
    user: telegraf:998
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_MOUNT_PREFIX=/hostfs
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var/run/utmp:/var/run/utmp:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - influxdb
    networks:
      - influxdb-network

  grafana:
    image: grafana/grafana:9.5.2
    user: "0"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=https://grafana.thinkpad.lr-projects.de
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana-config/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb
    networks:
      - influxdb-network
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.thinkpad.lr-projects.de`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=cloudflare
      - traefik.http.services.grafana.loadbalancer.server.port=3000

networks:
  influxdb-network:
    external: true
  frontend:
    external: true
