services:
  nextcloud:
    image: nextcloud:latest
    restart: always
    volumes:
      - nextcloud:/var/www/html
    networks:
      - frontend
      - backend-nextcloud
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.thinkpad.lr-projects.de`)
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.tls.certresolver=cloudflare
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-middlewares-secure-headers"
      - "traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.featurePolicy=camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
      - "traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.customResponseHeaders.X-Robots-Tag=none"
      - "traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.customResponseHeaders.server=" # This removes the "server" header
      - "traefik.docker.network=frontend" # This should hopefully fix the bad gateway error
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - REDIS_HOST_PASSWORD=redis
      - REDIS_HOST=redis
    depends_on:
      - database
      - redis
    dns:
      - 10.217.236.1
      - 8.8.8.8

  database:
    image: mariadb:11.4
    restart: always
    networks:
      - backend-nextcloud
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
    volumes:
      - database:/var/lib/mysql

  redis:
    networks:
      - backend-nextcloud
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  nextcloud:
  database:
networks:
  frontend:
    external: true
  backend-nextcloud:
