http:
  routers:
    # =====================
    # Zoom 0-6
    # =====================
    map-0-6:
      rule: "Host(`map.lr-projects.de`) && PathRegexp(`^/tile/(0|1|2|3|4|5|6)/([0-9]+)/([0-9]+)(.*)$`)"
      entryPoints:
        - websecure
      tls: true
      service: noop@internal
      middlewares:
        - tile-zoom-0-6

    # =====================
    # Zoom 7-9
    # =====================
    map-7-9:
      rule: "Host(`map.lr-projects.de`) && PathRegexp(`^/tile/(7|8|9)/([0-9]+)/([0-9]+)(.*)$`)"
      entryPoints:
        - websecure
      tls: true
      service: noop@internal
      middlewares:
        - tile-zoom-7-9

    # =====================
    # Zoom 10-12
    # =====================
    map-10-12:
      rule: "Host(`map.lr-projects.de`) && PathRegexp(`^/tile/(1[0-2])/([0-9]+)/([0-9]+)(.*)$`)"
      entryPoints:
        - websecure
      tls: true
      service: noop@internal
      middlewares:
        - tile-zoom-10-12

    # =====================
    # Zoom 13-14
    # =====================
    map-13-14:
      rule: "Host(`map.lr-projects.de`) && PathRegexp(`^/tile/(1[3-4])/([0-9]+)/([0-9]+)(.*)$`)"
      entryPoints:
        - websecure
      tls: true
      service: noop@internal
      middlewares:
        - tile-zoom-13-14

    # =====================
    # Zoom 14-16
    # =====================
    map-14-16:
      rule: "Host(`map.lr-projects.de`) && PathRegexp(`^/tile/(1[4-6])/([0-9]+)/([0-9]+)(.*)$`)"
      entryPoints:
        - websecure
      tls: true
      service: noop@internal
      middlewares:
        - tile-zoom-14-16

    # =====================
    # Default fallback
    # =====================
    map-default:
      rule: "Host(`map.lr-projects.de`) && PathRegexp(`^/tile/([0-9]+)/([0-9]+)/([0-9]+)(.*)$`)"
      entryPoints:
        - websecure
      tls: true
      service: noop@internal
      priority: 1
      middlewares:
        - tile-zoom-default

  middlewares:
    tile-zoom-0-6:
      redirectRegex:
        regex: "(.*)/tile/([0-6]+)/([0-9]+)/([0-9]+)(.*)"
        replacement: "https://tiles.stadiamaps.com/tiles/outdoors/${2}/${3}/${4}.png?api_key={{ env `API_KEY_0_6` }}"
        permanent: true

    tile-zoom-7-9:
      redirectRegex:
        regex: "(.*)/tile/([7-9]+)/([0-9]+)/([0-9]+)(.*)"
        replacement: "https://tiles.stadiamaps.com/tiles/outdoors/${2}/${3}/${4}.png?api_key={{ env `API_KEY_7_9` }}"
        permanent: true

    tile-zoom-10-12:
      redirectRegex:
        regex: "(.*)/tile/(1[0-2])/([0-9]+)/([0-9]+)(.*)"
        replacement: "https://tiles.stadiamaps.com/tiles/outdoors/${2}/${3}/${4}.png?api_key={{ env `API_KEY_10_12` }}"
        permanent: true

    tile-zoom-13-14:
      redirectRegex:
        regex: "(.*)/tile/(1[3-4])/([0-9]+)/([0-9]+)(.*)"
        replacement: "https://tiles.stadiamaps.com/tiles/outdoors/${2}/${3}/${4}.png?api_key={{ env `API_KEY_13_14` }}"
        permanent: true

    tile-zoom-14-16:
      redirectRegex:
        regex: "(.*)/tile/(1[4-6])/([0-9]+)/([0-9]+)(.*)"
        replacement: "https://tiles.stadiamaps.com/tiles/outdoors/12/${2}/${3}.png?api_key={{ env `API_KEY_14_16` }}"
        permanent: true

    tile-zoom-default:
      redirectRegex:
        regex: "(.*)/tile/([0-9]+)/([0-9]+)/([0-9]+)(.*)"
        replacement: "https://tiles.stadiamaps.com/tiles/outdoors/${2}/${3}/${4}.png?api_key={{ env `API_KEY_DEFAULT` }}"
        permanent: true
