backends:
  drive:
    type: rclone
    path: drive_lr101:backup/thinkpad
    key: ""
    requirekey: false
    env: {}
    rest:
      user: ""
      password: ""
    options: {}
  nas:
    type: sftp
    path: nas:/backup_thinkpad
    key: ""
    requirekey: false
    env: {}
    rest:
      user: ""
      password: ""
    options: {}
global:
  forget:
    keep-daily: 4
    keep-last: 5
    keep-monthly: 12
    keep-weekly: 1
    keep-yearly: 7
    retry-lock: 10
locations:
  bitwarden:
    from:
    - ./bitwarden
    type: ""
    to:
    - drive
    - nas
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success:
      - python3 ../scripts/influx-hook.py --host thinkpad --service bitwarden --status
        success
      failure:
      - python3 ../scripts/influx-hook.py --host thinkpad --service bitwarden --status
        failure
    cron: ""
    options: {}
    copyoption: {}
  docker-tags:
    from:
    - ./.backup
    type: ""
    to:
    - nas
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before:
      - |
        docker ps -q | while read cid; do
          cname=$(docker inspect -f '{{.Name}}' "$cid" | sed 's#^/##')
          image=$(docker inspect -f '{{.Config.Image}}' "$cid")
          digest=$(docker image inspect "$image" --format '{{index .RepoDigests 0}}' 2>/dev/null || echo "none")
          printf "%s\t%s\t%s\n" "$cname" "$image" "$digest"
        done > ./.backup/docker-tags.txt
      after: []
      success:
      - python3 ../scripts/influx-hook.py --host thinkpad --service docker-tags --status
        success
      failure:
      - python3 ../scripts/influx-hook.py --host thinkpad --service docker-tags --status
        failure
    cron: ""
    options: {}
    copyoption: {}
  glance:
    from:
    - ./glance
    type: ""
    to:
    - nas
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success:
      - python3 ../scripts/influx-hook.py --host thinkpad --service glance --status
        success
      failure:
      - python3 ../scripts/influx-hook.py --host thinkpad --service glance --status
        failure
    cron: ""
    options: {}
    copyoption: {}
  ha:
    from:
    - ./ha
    type: ""
    to:
    - nas
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success:
      - python3 ../scripts/influx-hook.py --host thinkpad --service ha --status success
      failure:
      - python3 ../scripts/influx-hook.py --host thinkpad --service ha --status failure
    cron: ""
    options: {}
    copyoption: {}
  monaserver:
    from:
    - ./monaserver
    type: ""
    to:
    - nas
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success:
      - python3 ../scripts/influx-hook.py --host thinkpad --service monaserver --status
        success
      failure:
      - python3 ../scripts/influx-hook.py --host thinkpad --service monaserver --status
        failure
    cron: ""
    options: {}
    copyoption: {}
  postgis:
    from:
    - ./postgis/backup
    type: ""
    to:
    - nas
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before:
      - python3 ../scripts/postgres-hook.py stick-it-db postgres stickitprod tempserver
        --backup-dir postgis/backup
      after: []
      success:
      - python3 ../scripts/influx-hook.py --host thinkpad --service postgis --status
        success
      failure:
      - python3 ../scripts/influx-hook.py --host thinkpad --service postgis --status
        failure
    cron: ""
    options: {}
    copyoption: {}
  tempserver:
    from:
    - ./tempserver
    type: ""
    to:
    - nas
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success:
      - python3 ../scripts/influx-hook.py --host thinkpad --service tempserver --status
        success
      failure:
      - python3 ../scripts/influx-hook.py --host thinkpad --service tempserver --status
        failure
    cron: ""
    options: {}
    copyoption: {}
  traefik:
    from:
    - ./traefik
    type: ""
    to:
    - nas
    - drive
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success:
      - python3 ../scripts/influx-hook.py --host thinkpad --service traefik --status
        success
      failure:
      - python3 ../scripts/influx-hook.py --host thinkpad --service traefik --status
        failure
    cron: ""
    options: {}
    copyoption: {}
version: 2
