- name: Home
  columns:
    - size: small
      widgets:

        - type: weather
          location: Bonn, Germany
          units: metric
          hour-format: 12h

        - type: dns-stats
          service: pihole-v6
          url: https://pihole.ionos.lr-projects.de
          username: admin
          password: ${PIHOLE_PSW}

        
        - type: bookmarks
          groups:
            - links:
                - title: Ionos
                  url: https://login.ionos.de
                - title: Cloudflare
                  url: https://dash.cloudflare.com/login
                - title: Amplify
                  url: https://amplify.nginx.com/dashboard
                - title: Play Console
                  url: https://play.google.com/console/developers/?pli=1
                - title: GitHub Profile
                  url: https://github.com/lr101
    - size: small
      widgets:
        - type: rss
          limit: 20
          collapse-after: 5
          cache: 15m
          feeds:
            - url: https://raumzeit.hka-iwi.de/api/v1/rssfeed/newsbulletinboard/IWI/INFM
              title: HKA INFM News

    - size: full
      widgets:
        - type: monitor
          cache: 5m
          title: Services (Public)
          sites:
            - title: Homepage
              url: https://lr-projects.de
              icon: https://lr-projects.de/_next/image?url=/icons/logo_lr_white.png&w=64&q=75
            - title: Stick-It Homepage
              url: https://stick-it-map.lr-projects.de
              icon: https://stick-it-map.lr-projects.de/_next/image?url=/icons/logo-round.png&w=64&q=75
            - title: Stick-It Backend
              url: https://stick-it.lr-projects.de/public/swagger-ui/index.html
              icon: https://stick-it-map.lr-projects.de/_next/image?url=/icons/logo-round.png&w=64&q=75
            - title: Stick-It OSM
              url: https://map.lr-projects.de/tile/0/0/0.png
              icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/openstreetmap.svg
            - title: Bitwarden
              url: https://bitwarden.lr-projects.de
              icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/bitwarden.svg
            - title: Nextcloud
              url: https://nextcloud.lr-projects.de
              icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/nextcloud.svg
        - type: monitor
          cache: 5m
          title: Services (Private)
          sites:
            - title: Grafana
              url: https://grafana.thinkpad.lr-projects.de
              icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/grafana.svg
            - title: Home Assistant
              url: http://10.217.236.3:8123
              icon: https://cdn.jsdelivr.net/gh/loganmarchione/homelab-svg-assets/assets/homeassistant.svg
            - title: Pi-Hole
              url: https://pihole.ionos.lr-projects.de/admin/login
              icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/pi-hole.svg
            - title: Nginx-UI
              url: https://nginx.ionos.lr-projects.de
              icon:	https://nginxui.com/assets/logo.svg
            - title: InfluxDB
              url: https://influx.thinkpad.lr-projects.de
              icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/influxdb.svg
            - title: Traefik Dashboard
              url: https://traefik.thinkpad.lr-projects.de/dashboard/#
              icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/traefik-proxy.svg
            - title: Nextcloud
              url: https://nextcloud.thinkpad.lr-projects.de/login
              icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/nextcloud-blue.svg
            - title: Minio Console
              url: https://minio-admin.thinkpad.lr-projects.de
              icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/minio-light.png
            - title: Blog
              url: https://ghost.lr-projects.de/ghost
              icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/ghost-light.png


