services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker containers widget
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env
    networks:
      - frontend
    dns:
      - 10.217.236.1
      - 8.8.8.8
    labels:
      - traefik.enable=true
      - traefik.http.routers.home.rule=Host(`home.thinkpad.lr-projects.de`)
      - traefik.http.routers.home.entrypoints=websecure
      - traefik.http.routers.home.tls=true
      - traefik.http.routers.home.tls.certresolver=cloudflare
      - traefik.http.services.home.loadbalancer.server.port=8080

networks:
  frontend:
    external: true
